version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@supabase/supabase-js"
    versions:
    - 1.11.3
    - 1.11.6
    - 1.11.7
    - 1.3.3
    - 1.3.4
    - 1.4.1
    - 1.4.2
    - 1.5.0
    - 1.5.1
    - 1.6.0
    - 1.7.0
  - dependency-name: swr
    versions:
    - 0.4.2
    - 0.5.0
    - 0.5.5
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: next
    versions:
    - 10.0.7
